server:
  port: 8088

project:
  version: @project.version@

MySQL:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: root

task:
  pool:
    corePoolSize: 5
    maxPoolSize: 20
    keepAliveSeconds: 300
    queueCapacity: 50

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MySQL.host}:${MySQL.port}/${MySQL.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: ${MySQL.username}
    password: ${MySQL.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
      maximum-pool-size: 12         # 最大连接数
      auto-commit: true             # 自动提交
      idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      pool-name: "数据库连接池" # 连接池名称
      max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
      connection-test-query: SELECT * FROM user WHERE 1

mybatis-plus:
  global-config:
    banner: false

shiro:
  limiter:
    enable: true
    rate: 1
    capacity: 1
    await-task: true
    timeout: 10
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 10
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 30
    # 线程池名前缀
    thread-name-prefix: "TaskPool-"
  ws-config:
    ws-url: "/qimenbot/ws/"
    # 超时回收，默认10秒
    do-request-timeout: 100000
    # 二进制消息的最大长度
    max-binary-message-buffer-size: 512000
    # 最大空闲时间，超过这个时间将close session
    max-session-idle-timeout: 900000
    # 最大文本消息缓冲区
    max-text-message-buffer-size: 512000
  plugin-list:
    - com.mryunqi.qimenbot.Plugin.Menu
    - com.mryunqi.qimenbot.Plugin.UserState
    - com.mryunqi.qimenbot.Plugin.Register
    - com.mryunqi.qimenbot.Plugin.ChangeSkill
    - com.mryunqi.qimenbot.Plugin.Alias
    - com.mryunqi.qimenbot.Plugin.Awake
    - com.mryunqi.qimenbot.Plugin.Position
    - com.mryunqi.qimenbot.Plugin.Cmd
    - com.mryunqi.qimenbot.Plugin.KanTui
    - com.mryunqi.qimenbot.Plugin.BackPack
    - com.mryunqi.qimenbot.Plugin.Transaction
    - com.mryunqi.qimenbot.Plugin.Challenge
    - com.mryunqi.qimenbot.Plugin.Battle
    - com.mryunqi.qimenbot.Plugin.UserSkill
    - com.mryunqi.qimenbot.Plugin.DemoPlugin
    - com.mryunqi.qimenbot.Plugin.SetUserSkill
    - com.mryunqi.qimenbot.Plugin.Comic
    - com.mryunqi.qimenbot.Plugin.PyExpand
    - com.mryunqi.qimenbot.Plugin.NovelAi
    - com.mryunqi.qimenbot.Plugin.HunHuanList
#'%d{hh:mm:ss} %-5level %logger{50} : %msg%n'
#logging:
  #pattern:
    #console: '[%d{yyyy:MM:dd hh:mm:ss}] [%-5level] : %msg%n'
    #file: '%d{hh:mm:ss} %-5level : %msg%n'




